source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CLTypingLabel_Example' do
  pod 'CLTypingLabel', :path => '../'
end

target 'CLTypingLabel_Tests' do
  pod 'CLTypingLabel', :path => '../'

  
end
